import bcrypt from 'bcryptjs';
import {
  CategoryRecord,
  ProviderRecord,
  ScholarshipRecord,
  UserRecord,
  StudentProfileRecord,
  AdminUserRecord,
} from '../types';

export const SEED_CATEGORIES: CategoryRecord[] = [
  {
    id: '11111111-1111-4111-a111-111111111111',
    name: 'STEM & Tech',
    slug: 'stem-tech',
    description: 'Computer Science, AI, Engineering, Mathematics, and Physical Sciences scholarships.',
    iconName: 'Cpu',
  },
  {
    id: '22222222-2222-4222-a222-222222222222',
    name: 'Health & Medicine',
    slug: 'health-medicine',
    description: 'Medicine, Biomedical Sciences, Nursing, Public Health, and Global Healthcare awards.',
    iconName: 'HeartPulse',
  },
  {
    id: '33333333-3333-4333-a333-333333333333',
    name: 'Business & Finance',
    slug: 'business-finance',
    description: 'Economics, MBA, International Trade, FinTech, and Entrepreneurship funding.',
    iconName: 'Briefcase',
  },
  {
    id: '44444444-4444-4444-a444-444444444444',
    name: 'Arts & Humanities',
    slug: 'arts-humanities',
    description: 'Literature, Philosophy, Visual Arts, History, and Cultural Studies programs.',
    iconName: 'Palette',
  },
  {
    id: '55555555-5555-4555-a555-555555555555',
    name: 'Undergraduate',
    slug: 'undergraduate',
    description: 'Bachelor degree scholarships, freshman entry grants, and undergraduate bursaries.',
    iconName: 'GraduationCap',
  },
  {
    id: '66666666-6666-4666-a666-666666666666',
    name: 'Postgraduate & PhD',
    slug: 'postgraduate-phd',
    description: 'Masters degrees, doctoral fellowships, and post-doctoral research endowments.',
    iconName: 'BookOpen',
  },
  {
    id: '77777777-7777-4777-a777-777777777777',
    name: 'Law & Public Policy',
    slug: 'law-public-policy',
    description: 'International Relations, Human Rights, Governance, and Legal Studies funding.',
    iconName: 'Scale',
  },
];

export const SEED_PROVIDERS: ProviderRecord[] = [
  {
    id: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',
    name: 'Bill & Melinda Gates Foundation',
    type: 'Global Philanthropic Foundation',
    logo: 'https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=128&h=128&fit=crop&crop=faces',
    website: 'https://www.gatesfoundation.org',
    description: 'Dedicated to fighting poverty, disease, and inequity around the world through educational access.',
    contactEmail: 'scholarships@gatesfoundation.org',
    country: 'United States',
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',
    name: 'Mastercard Foundation',
    type: 'International NGO',
    logo: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=128&h=128&fit=crop&crop=faces',
    website: 'https://mastercardfdn.org',
    description: 'Working with visionary organizations to enable young people in Africa to access education and financial services.',
    contactEmail: 'scholars@mastercardfdn.org',
    country: 'Canada',
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cccccccc-cccc-4ccc-cccc-cccccccccccc',
    name: 'Rhodes Trust',
    type: 'Endowment Educational Trust',
    logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&h=128&fit=crop&crop=faces',
    website: 'https://www.rhodeshouse.ox.ac.uk',
    description: 'The oldest and perhaps most prestigious international scholarship programme in the world, enabling young leaders to study at Oxford.',
    contactEmail: 'scholarships@rhodeshouse.ox.ac.uk',
    country: 'United Kingdom',
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dddddddd-dddd-4ddd-dddd-dddddddddddd',
    name: 'Fulbright Foreign Student Program',
    type: 'Government Exchange Program',
    logo: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=128&h=128&fit=crop&crop=faces',
    website: 'https://foreign.fulbrightonline.org',
    description: 'Enables graduate students, young professionals and artists from abroad to study and conduct research in the United States.',
    contactEmail: 'fulbright@state.gov',
    country: 'United States',
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'eeeeeeee-eeee-4eee-eeee-eeeeeeeeeeee',
    name: 'DAAD German Academic Exchange Service',
    type: 'Government Agency',
    logo: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=128&h=128&fit=crop&crop=faces',
    website: 'https://www.daad.de/en/',
    description: 'The world\'s largest funding organization for the international exchange of students and researchers.',
    contactEmail: 'poststelle@daad.de',
    country: 'Germany',
    verified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_SCHOLARSHIPS: ScholarshipRecord[] = [
  {
    id: 'sch-001',
    title: 'Gates Cambridge Global Scholars Program',
    providerId: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',
    providerName: 'Bill & Melinda Gates Foundation',
    providerLogo: 'https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=128&h=128&fit=crop&crop=faces',
    description: 'Full-cost awards for outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree in any subject available at the University of Cambridge.',
    shortDescription: 'Prestigious full-cost postgraduate funding for international students at Cambridge University.',
    category: 'Postgraduate & PhD',
    tags: ['Full Tuition', 'Stipend', 'Airfare', 'Cambridge'],
    amount: 55000,
    currency: 'GBP',
    fundingType: 'Fully funded',
    eligibleCountries: ['All'],
    educationLevels: ['Postgraduate (Masters)', 'Doctorate (PhD)'],
    fieldsOfStudy: ['All'],
    minimumGPA: 3.7,
    gpaScale: 4.0,
    genderRequirement: 'Any',
    financialNeedRequired: false,
    requiredDocuments: [
      'Academic Transcripts',
      'Curriculum Vitae (CV)',
      'Research Proposal',
      'Two Academic References',
    ],
    applicationInstructions: 'Apply directly via the Cambridge Applicant Portal by submitting the Graduate Application Form alongside the Gates Cambridge section.',
    applicationUrl: 'https://www.gatescambridge.org/apply/',
    openingDate: '2026-09-01T00:00:00Z',
    deadline: '2026-12-05T23:59:59Z',
    status: 'verified',
    verificationStatus: 'verified',
    viewCount: 1420,
    saveCount: 312,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-002',
    title: 'Mastercard Foundation Scholars at Oxford',
    providerId: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',
    providerName: 'Mastercard Foundation',
    providerLogo: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=128&h=128&fit=crop&crop=faces',
    description: 'Comprehensive scholarship providing fully-funded Masters study at the University of Oxford for students from Sub-Saharan Africa facing significant financial hardship.',
    shortDescription: 'Fully-funded Masters scholarships at Oxford for talented African students.',
    category: 'Postgraduate & PhD',
    tags: ['Africa', 'Masters', 'Fully Funded', 'Oxford', 'Leadership'],
    amount: 48000,
    currency: 'GBP',
    fundingType: 'Fully funded',
    eligibleCountries: ['Nigeria', 'Kenya', 'Ghana', 'Rwanda', 'South Africa', 'Uganda', 'Ethiopia', 'Tanzania'],
    educationLevels: ['Postgraduate (Masters)'],
    fieldsOfStudy: ['All'],
    minimumGPA: 3.5,
    gpaScale: 4.0,
    financialNeedRequired: true,
    genderRequirement: 'Any',
    requiredDocuments: [
      'Academic Transcripts',
      'Personal Statement of Leadership',
      'Financial Need Assessment Form',
      'Three Letters of Recommendation',
    ],
    applicationInstructions: 'Submit your regular graduate application to the University of Oxford and select the Mastercard Foundation Scholarship checkbox.',
    applicationUrl: 'https://www.ox.ac.uk/admissions/graduate/fees-and-funding/fees-funding-and-scholarships/search/mastercard-foundation-scholarships',
    openingDate: '2026-09-15T00:00:00Z',
    deadline: '2026-11-20T23:59:59Z',
    status: 'verified',
    verificationStatus: 'verified',
    viewCount: 980,
    saveCount: 245,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-003',
    title: 'Rhodes Scholarship for International Leaders',
    providerId: 'cccccccc-cccc-4ccc-cccc-cccccccccccc',
    providerName: 'Rhodes Trust',
    providerLogo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&h=128&fit=crop&crop=faces',
    description: 'Postgraduate awards supporting exceptional young people from around the world to study at the University of Oxford, fostering transformative leadership.',
    shortDescription: 'World-renowned postgraduate scholarship to Oxford University.',
    category: 'Arts & Humanities',
    tags: ['Oxford', 'Leadership', 'Full Grant', 'Global'],
    amount: 60000,
    currency: 'GBP',
    fundingType: 'Fully funded',
    eligibleCountries: ['All'],
    educationLevels: ['Postgraduate (Masters)', 'Doctorate (PhD)'],
    fieldsOfStudy: ['All'],
    minimumGPA: 3.8,
    gpaScale: 4.0,
    minimumAge: 18,
    maximumAge: 25,
    genderRequirement: 'Any',
    requiredDocuments: [
      'Certified Transcripts',
      'Comprehensive CV',
      'Personal Statement (1000 words)',
      'Five to Eight Letters of Reference',
      'Institutional Endorsement',
    ],
    applicationInstructions: 'Applications must be submitted through your respective national constituency portal or the Global Rhodes portal.',
    applicationUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/applications/',
    openingDate: '2026-06-01T00:00:00Z',
    deadline: '2026-10-01T23:59:59Z',
    status: 'verified',
    verificationStatus: 'verified',
    viewCount: 2310,
    saveCount: 680,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-004',
    title: 'Fulbright Foreign Student Exchange Award',
    providerId: 'dddddddd-dddd-4ddd-dddd-dddddddddddd',
    providerName: 'Fulbright Foreign Student Program',
    providerLogo: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=128&h=128&fit=crop&crop=faces',
    description: 'Enables graduate students, young professionals and artists from 160+ countries to study and conduct research at premier universities in the United States.',
    shortDescription: 'Study and research fellowships in the United States for international graduates.',
    category: 'STEM & Tech',
    tags: ['USA', 'Exchange', 'Tuition', 'Health Insurance'],
    amount: 45000,
    currency: 'USD',
    fundingType: 'Fully funded',
    eligibleCountries: ['All'],
    educationLevels: ['Postgraduate (Masters)', 'Doctorate (PhD)'],
    fieldsOfStudy: ['Engineering', 'Computer Science', 'Public Health', 'Economics'],
    minimumGPA: 3.3,
    gpaScale: 4.0,
    genderRequirement: 'Any',
    requiredDocuments: [
      'Official Academic Records',
      'Statement of Purpose',
      'Study/Research Objectives',
      'TOEFL/IELTS Score Report',
      'Three Letters of Recommendation',
    ],
    applicationInstructions: 'Program eligibility and selection procedures vary widely by country. Check your local US Embassy or Fulbright Commission website.',
    applicationUrl: 'https://foreign.fulbrightonline.org/about/foreign-student-program',
    openingDate: '2026-02-01T00:00:00Z',
    deadline: '2026-10-15T23:59:59Z',
    status: 'verified',
    verificationStatus: 'verified',
    viewCount: 1650,
    saveCount: 420,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-005',
    title: 'DAAD Helmut-Schmidt-Programme in Public Policy & Good Governance',
    providerId: 'eeeeeeee-eeee-4eee-eeee-eeeeeeeeeeee',
    providerName: 'DAAD German Academic Exchange Service',
    providerLogo: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=128&h=128&fit=crop&crop=faces',
    description: 'Supports future leaders from developing and emerging countries in fields of social sciences, law, and economics at leading German institutions.',
    shortDescription: 'Full Master funding at German universities for students from emerging nations.',
    category: 'Law & Public Policy',
    tags: ['Germany', 'Europe', 'Public Policy', 'Monthly Allowance'],
    amount: 32000,
    currency: 'EUR',
    fundingType: 'Fully funded',
    eligibleCountries: ['Developing Countries', 'Nigeria', 'India', 'Brazil', 'Kenya', 'Indonesia'],
    educationLevels: ['Postgraduate (Masters)'],
    fieldsOfStudy: ['Political Science', 'Law', 'Economics', 'Public Administration'],
    minimumGPA: 3.2,
    gpaScale: 4.0,
    genderRequirement: 'Any',
    requiredDocuments: [
      'Undergraduate Degree Certificate',
      'Motivation Letter',
      'Language Proficiency Certificate (English/German)',
      'Current CV in Europass Format',
    ],
    applicationInstructions: 'Applications must be submitted directly to the selected German universities offering Helmut-Schmidt courses.',
    applicationUrl: 'https://www.daad.de/en/information-services-for-higher-education-institutions/further-information-on-daad-programmes/helmut-schmidt-programme/',
    openingDate: '2026-06-01T00:00:00Z',
    deadline: '2026-07-31T23:59:59Z',
    status: 'verified',
    verificationStatus: 'verified',
    viewCount: 840,
    saveCount: 190,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sch-006',
    title: 'NextGen Women in Computer Science & AI Fellowship',
    providerId: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',
    providerName: 'Bill & Melinda Gates Foundation',
    providerLogo: 'https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=128&h=128&fit=crop&crop=faces',
    description: 'Accelerating gender equality in computing and artificial intelligence through undergraduate bursaries, mentorship, and industry internship placements.',
    shortDescription: 'Undergraduate tuition grants and career mentorship for women studying Computer Science and AI.',
    category: 'STEM & Tech',
    tags: ['Women in Tech', 'Artificial Intelligence', 'Undergraduate', 'Mentorship'],
    amount: 25000,
    currency: 'USD',
    fundingType: 'Partial funding',
    eligibleCountries: ['All'],
    educationLevels: ['Undergraduate'],
    fieldsOfStudy: ['Computer Science', 'Artificial Intelligence', 'Software Engineering', 'Data Science'],
    minimumGPA: 3.4,
    gpaScale: 4.0,
    genderRequirement: 'Female',
    financialNeedRequired: false,
    requiredDocuments: [
      'Current University Transcript',
      'GitHub or Technical Project Portfolio',
      'Personal Essay on AI Ethics',
      'One Academic Reference',
    ],
    applicationInstructions: 'Submit your project link and resume through the foundation education portal.',
    applicationUrl: 'https://www.gatesfoundation.org/ideas/articles/women-in-stem-grants',
    openingDate: '2026-08-01T00:00:00Z',
    deadline: '2026-11-30T23:59:59Z',
    status: 'pending_verification',
    verificationStatus: 'pending_verification',
    viewCount: 310,
    saveCount: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export async function createInitialSeedUsers(): Promise<{
  adminUser: UserRecord;
  adminUser2: UserRecord;
  demoStudent: UserRecord;
  demoProfile: StudentProfileRecord;
  adminDirectoryUser: AdminUserRecord;
  adminDirectoryUser2: AdminUserRecord;
}> {
  const adminPasswordHash = await bcrypt.hash('admin123', 10);
  const studentPasswordHash = await bcrypt.hash('student123', 10);

  const adminUser: UserRecord = {
    id: 'usr-admin-001',
    email: 'admin@scholarpath.org',
    passwordHash: adminPasswordHash,
    role: 'admin',
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const adminDirectoryUser: AdminUserRecord = {
    id: 'usr-admin-001',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'admin@scholarpath.org',
    role: 'Super Admin',
    status: 'Active',
    assignedDepartment: 'Operations & Verification',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  };

  const adminUser2: UserRecord = {
    id: 'usr-admin-002',
    email: 'chrisekpe18@gmail.com',
    passwordHash: adminPasswordHash,
    role: 'admin',
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const adminDirectoryUser2: AdminUserRecord = {
    id: 'usr-admin-002',
    firstName: 'Chris',
    lastName: 'Ekpe',
    email: 'chrisekpe18@gmail.com',
    role: 'Admin',
    status: 'Active',
    assignedDepartment: 'Scholarship Operations',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  };

  const demoStudent: UserRecord = {
    id: 'usr-student-001',
    email: 'student@scholarpath.org',
    passwordHash: studentPasswordHash,
    role: 'student',
    emailVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const demoProfile: StudentProfileRecord = {
    userId: 'usr-student-001',
    firstName: 'Alex',
    lastName: 'Morgan',
    email: 'student@scholarpath.org' as any,
    country: 'International',
    educationLevel: 'Undergraduate',
    institution: 'Tech Institute of Science',
    fieldOfStudy: 'Computer Science',
    course: 'B.Sc Software Engineering',
    gpa: 3.85,
    gpaScale: 4.0,
    profileCompletion: 85,
    awards: ['Dean\'s Honour Roll 2025', 'National Coding Olympiad Finalist'],
    achievements: ['Published paper on Neural Search in IEEE Student branch'],
    certifications: ['AWS Certified Cloud Practitioner'],
    notificationPreferences: {
      inApp: true,
      email: true,
      deadlineAlerts: true,
      matchingAlerts: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  return { adminUser, adminUser2, demoStudent, demoProfile, adminDirectoryUser, adminDirectoryUser2 };
}
